@baseUrl = http://localhost:3000

### Register Admin
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Admin User",
  "email": "admin@example.com",
  "password": "admin123456"
}

### Register User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Regular User",
  "email": "user@example.com",
  "password": "user123456"
}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin123456"
}

### Get Profile
@token = {{login.response.body.token}}
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}
